name: Trigger auto deployment for app-back

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/app-back-AutoDeployTrigger-caa801d7-12b3-447f-a734-cfb0f9367539.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APPBACK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPBACK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPBACK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.APPBACK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPBACK_REGISTRY_PASSWORD }}
          containerAppName: app-back
          resourceGroup: mine-ts-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


